version: '3.6'
services:
  web:
    build: ./web
    deploy:
      replicas: 4
    expose:
      - 5000

  
  
  nginx:
    build: ./nginx
    links:
      - web
    ports:
      - "80:80"
    expose:
      - 80
    depends_on:
      - web
      - worker1
      - worker2
      - queue

  worker1:
    build: ./workers/worker1
    
    ports:
      - "4001:4001"
    expose:
      - 4001
  
  worker2:
    build: ./workers/worker2
    
    ports:
      - "4002:4002"
    expose:
      - 4002
  queue:
    build: ./queue
    links:
      - web
      - worker1
      - worker2
    ports: 
      - "3000:3000"
    expose:
      - 3000